license = "BSD3"
with_readme = true

[files]
directories = ["src", "app", "ats-src", "cbits"]
templates = ["src/Lib.hs", "shake.hs", "{{ project }}.cabal", "Setup.hs", "app/Main.hs", "cabal.project.local"]

[config]
version = "0.1.0.0"
version_control = "git"
